Lil tweaks at the 'Integration Test' section

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,8 +28,9 @@ jobs:
       - name: Integration Test
         run: |
           $output = .\target\expense-tracker.exe -d "Teste Pipeline" -v 100
-          if ($output -like "*Processando... Teste Pipeline*") { 
+          if ($output -like "*Processando...\nDescricao: Teste Pipeline*") { 
             echo "Test passed!" 
           } else { 
-            echo "Test failed!"; exit 1 
+            echo "Test failed!"
+            echo $output; exit 1 
           }
